### ISSUE TITLE
Problem statement, precedence, alternatives considered and polyfill/transpillation patterns?

### ISSUE THREAD

**Issue by samuelgoto** [michaelficarra/proposal-first-class-protocols#16]
I generally really like this area and I think there are tons of opportunities to be explored here.

Can you help me understand more precisely the problem you are trying to solve (I get the general idea but this seems like there is a big surface area with a lot of intersections)?

More specifically, can you help me understand:

1. how each language solves this differently (you mention java 8 interfaces and other precedent in other languages) and what trade-offs were considered (e.g. what works and what doesn't work so well)?
2. what alternatives were considered? What’s the distinction between traits and mixins, which one you are favoring (if any?) and what are the trade-offs between them?
3. i’m assuming that this has nothing to do with a type system (neither gradual nor optional) but can you make that explicit somewhere and have an articulation around the relationship here (fine if the answer is “no relationship”)?
4. what are the patterns that we have seen in the industry? How many of them can be done without any language extension (extends mixin() expressions)? Which ones can’t (and have to be transpilled)? Is this a syntactic sugar for a very simple simplification (if so, what's the simplification) or does it go beyond syntactic sugar? Which polyfill would this help and which wouldn’t (polymer?)?
5. why does this need to be baked into the language? can one (or should one?) create a transpiller for this instead (e.g. babel plugin)? does one exist? if so, is it popular? if not (exists/is popular), why not?

This seems like it would be valuable content to be added to the README for most readers of your proposal as background research.

**Comment by michaelficarra** [comment]
Thanks for the questions, @samuelgoto!

1. I have a [Relationships to Similar Features](https://github.com/michaelficarra/proposal-first-class-protocols#relationship-to-similar-features) section in the README. It's not completely filled out, but I'll try to fill it out the remaining TODOs before I present next week. 

2. The best alternative we have today is either implementing this pattern manually or abusing inheritance to use the mixin pattern described in the README.

3. The answer is indeed "no relationship". As I describe in the comparison to Haskell's type classes, a type system could be used to automatically resolve implementations, but because we don't have one, we are explicit about which implementation we use. This is actually better in some ways.

4. This pattern is being used frequently by language built-ins, but it is not being used much by industry outside of the built-in protocols. This proposal isn't strictly necessary to use this pattern.

5. Baking it into the language reduces the cost of adopting this pattern, and will, in my opinion, foster an ecosystem of reusable, complete, well-tested protocols. A rich ecosystem like this exists for Haskell users and has shown its value. If the committee would like to pursue this direction (stage 1), we will create a babel plugin. A sweet.js implementation already exists (though could use an update for recent changes).

I'll try to make sure each of these questions is addressed by the README and then close this issue out.
