### ISSUE TITLE
allow required strings in addition to required symbols

### ISSUE THREAD

**Issue by michaelficarra** [michaelficarra/proposal-first-class-protocols#19]
This is a heavily requested feature from some TC39 delegates. I can imagine a syntax like

```js
protocol A {
  "string-named-property";
  // rest as normal
}
```

**Comment by ljharb** [comment]
Would that mean that to write a protocol that matches a pre-symbol object, i'd be limited to only specifying string-named properties (as opposed to a string-named method implementation)?

**Comment by michaelficarra** [comment]
I don't know what you mean. Function-valued properties are methods. The name is unrelated.

**Comment by baptistemanson** [comment]
I don't encounter symbols often which penalized my understanding of this specs. I crossed a polyfill of Symbols used in React source code once. Does this adjustment will make the usage of protocols more approachable, or learning what are the symbols will still be a prerequisite to the protocols usage?

**Comment by keithamus** [comment]
Symbols are necessary for the proposal but are effectively opaque - you dont really need to know what Symbols are to use this. Symbols are an "under the hood" part of this proposal - you would only refer to them by the protocol name:

```js
protocol Foo {
  bar
}

typeof Foo.bar === "Symbol"
```

**Comment by weswigham** [comment]
@keithamus Symbols aren't under the hood - they're used directly by implementers, ie
```js
protocol Foo {
  bar
}

class FooImpl implements Foo {
  [Foo.bar]() { // This can't be implemented unless you have the symbol stored at `Foo.bar`
    // ...
  }
}
```

Whereas string members would allow structural implementations which don't even need to have access to the protocol:

```js
// implementer.js
export class FileDescriptor {
  // ...
  finalize() {
    this.flush();
    this.close();
  }
}

// consumer.js
protocol Finalizable {
  "finalize";
}

const potentialImplementers = [(await import("https://cdn.com/implementer.js")).FileDescriptor];

for (const cls of potentialImplementers) {
  if (cls.prototype.hasOwnProperty("finalize") && typeof cls.prototype.finalize === "function") {
    Protocol.implement(cls, Finalizable);
  }
}

// some time later
for (const instance of instantiated) {
  if (instance implements Finalizable) { // Now we can use this operator, rather than some flag we would have stored on the prototype
    instance.finalize(); // Known safe because of the above check coupled with the addition of this implements by initialization code
  }
}
```

This maps much better to _existing_ code, where symbols do not see that much use. String-named members are also more natural to use/call, which is not something to be so simply overlooked! I, for one, would always rather `instance.method()` than `instance[SomeProtocol.method]()` (both while calling or implementing) if possible. Symbols are certainly useful for specifying which protocol's implementation you'd like to see... however, strings would allow this to see more widespread deployment alongside existing code.

**Comment by keithamus** [comment]
> Symbols aren't under the hood

You didn't refer to the `Symbol` function once in your code; I'd call that under the hood.

> This maps much better to _existing_ code, where symbols do not see that much use

Agreed.

> I, for one, would always rather `instance.method()` than `instance[SomeProtocol.method]()`

I think, in practice, you're unlikely to use either. I'll point; for example; Ramda's functions, which make use of both Fantasy-land and Transducers.js; for example [the source for `map`](https://github.com/ramda/ramda/blob/v0.24.1/src/map.js) delegates to `functor['fantasy-land/map']` - which in a world with protocols would look something like `functor[FantasyLand.map]`. Similarly; `map` also doubles as a mapping transducer, which right now has the protocol of `.prototype['@@transducer/init']`, `.prototype['@@transducer/step']`, `.prototype['@@transducer/result']`, and `.prototype['@@transducer/return']`. In both of these cases; protocols would be useful for library implementors but application code never sees these underlying Protocol structures. In Ramda, you just call `map` and it does this _under the hood_.

To give another example; JavaScript of today has a built in protocol: iterators. Iterators use `[Symbol.iterator]()` as a method, that should return an object of `next()` and (optionally) `return()`. In practice application code never consumes any of these; Generator Functions give you the facility to make an iterator that implements `next()` for each `yield`, and `[Symbol.iterator]()` is triggered when you `for(x of thingThatImplementsProtocol)`. So again, application code rarely sees the surface area of this protocol; instead opting for convenience grammars that de-sugar.

I'll add a concrete _counterpoint_ to the concept of string based protocols: that is the "thenable" protocol. Having this protocol using strings causes a whole slew of problems; if I pass a Promise any class with a `.then()` method it automatically assumes that `then` method to have a certain signature (`then<T,R>((T: any) => Promise<R>|R, (Error) => Promise<R>|R) => Promise<R>`) and _will_ invoke it as it is consumed by promises. This has now effectively made `then` a _halfway reserved word_ (in that it is not explicitly disallowed, but anything other than using the Promise signature is assured to break code). If we used Symbol based protocols we could solve this entire mess.

In addition; String methods are limited in scope to what is allowed in identifier names, while Symbols are effectively infinite. If my library implements a `Functor` protocol, to which I add `map` (which should be a function that takes a unary function and returns an instance) - but I want to be compatible with your library which offers a _different_ kind of map method (lets say you call yours `Iterator.map` and it should return an iterator); Symbol based protocols allow me to support both (because `Functor.map !== Foo.map`).

Adding string method names for Protocols is an acceptably pragmatic solution to getting this through standards; but the community ..."thought leadership"... should be strongly encouraging the use of Symbols as it is the best way to implement protocols. Yes, Symbols are hard to grok. Yes, calling `instance[SomeProtocol.method]()` is a bit awkward. These two factors do not outweigh the problems though.

**Comment by ljharb** [comment]
Fully agree with https://github.com/michaelficarra/proposal-first-class-protocols/issues/19#issuecomment-333497930 - strings imo are necessary precisely *because* "thenable" and "arraylike" are two builtin protocols that the language should be able to represent, and there are doubtless tons of userland protocols that could be represented with strong properties - so while strings are necessary for a seamless transition, *new* protocols should all use Symbols.
