### ISSUE TITLE
Protocol overriding order

### ISSUE THREAD

**Issue by HerringtonDarkholme** [michaelficarra/proposal-first-class-protocols#20]
I wonder how protocols override. That is:

```js
protocol I {
  a
}

protocol A {
  [I.a]() { return 0 }
}

protocol B {
  [I.a]() { return 1 }
}

class C implements A, B {}

assert((new C)[I.a]()) // 0 or 1?
```

I didn't see mixing two protocols with conflicting symbols in the spec. Apologize in advance if I missed it.

**Comment by nicolo-ribaudo** [comment]
Do protocols actually support computed keys?

**Comment by ljharb** [comment]
I believe that the implements test just does an "in" check; so `C implements A` and `C implements B` would both be true; similarly, the only thing that would make any sense is if B's implementation won out.

Thus, 1.

**Comment by michaelficarra** [comment]
@HerringtonDarkholme You can always try these things out in [the sweet.js implementation](https://github.com/disnet/sweet-interfaces). I've added a test there to show you how this works: https://github.com/disnet/sweet-interfaces/commit/12813051638770804fbe0d46cddfb0a5b28ce52e. The tl;dr is interface copying avoids overwriting existing properties (so a specific class can implement a better/more optimised version of a general interface method). So the order matters here.

@nicolo-ribaudo Yes, all property keys are supported.

@ljharb This example is not using the binary `implements` operator. It is using a class declaration with the optional `implements` clause. See above; this returns 0 because interface copying does not overwrite.

**Comment by ljharb** [comment]
@michaelficarra is my reasoning about the test operator correct?

**Comment by michaelficarra** [comment]
@ljharb Yes, the `implements` operator very simply does a test that each of the property names that are required/provided by the right operand are present in the left operand (`in` semantics).

**Comment by HerringtonDarkholme** [comment]
I would agree on @ljharb 's idea that last protocol wins. Since it works more like prototype chain that last come last win.

**Comment by ljharb** [comment]
Ftr while I find it surprising that the first value under the property wins, I like the goal (which is to not overwrite an explicitly present implementation). Since the syntax is sugar for Reflect.implement calls, and the goal after such a call is that the testing operator returns true, this makes sense to me, and I think it's the right choice.

**Comment by michaelficarra** [comment]
@HerringtonDarkholme I think that would be a strange inconsistency with how properties that are present in classes effectively "override" the ones provided by any interfaces they implement. Currently, the precedence order in `class A implements B, C {}` is `A > B > C`, and I think that is less confusing than `A > C > B`.

**Comment by michaelficarra** [comment]
@ljharb `Protocol.implement` :wink:

**Comment by ljharb** [comment]
lol sorry, fixed

**Comment by HerringtonDarkholme** [comment]
After more thoughts, I think a better choice is reporting error when two interfaces has conflicting default methods. 

This is a common behavior for many languages, like Java and PHP. 

ref: 
https://docs.oracle.com/javase/specs/jls/se9/html/jls-9.html#jls-9.4.1.3

**Comment by michaelficarra** [comment]
@HerringtonDarkholme That may solve some of the concerns @wycats raised during the presentation to TC39. I will continue to consider that as the proposal develops.

**Comment by hax** [comment]
Not sure whether it should be given a resolve order, or just throw error.

Even given a order (like https://en.wikipedia.org/wiki/C3_linearization), multiple inheritance may still be headache  (like B implements A; C implements B; D implements A; E implements C, D => now practise how to resolve the methods on A for E 😁 ) 

FYI the trait libraries in the wild (like https://github.com/traitsjs/traits.js or it's grandfarther lib https://github.com/mozilla/addon-sdk-sdocs/blob/master/sdk/Firefox-23/module-source/sdk/deprecated/light-traits.md) choose reporting errors if no explicit resolve.
